![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [18]:
import numpy as np

my_array = np.arange(0,10)
print(my_array)

print(my_array[ -1:0:-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [19]:
my_array[-2:-4:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [21]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [30]:
my_array = np.arange(1,21).reshape((4,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
my_array[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [35]:
my_array[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [40]:
my_array[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [42]:
my_array[:3, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [43]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [49]:
mascara_condicion = x == "Loro"
x[mascara_condicion]

array(['Loro', 'Loro'], dtype='<U5')

In [65]:
mascara_2 = x != "Loro"
np.where(mascara_2,None ,x)

array(['Loro', None, None, 'Loro', None], dtype=object)

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [77]:
np.arange(1,21).reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [83]:
my_array = np.arange(1,21).reshape(2,5,2).reshape(4,-1)

my_array[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [101]:
array_ceros= np.zeros(10)
print(array_ceros)
print("Ocupa de memoria: ",array_ceros.itemsize)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ocupa de memoria:  8


In [97]:
mascara = array_ceros[4] == 1
array_ceros[mascara]

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [114]:
np.arange(10,50)[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [129]:
# Broadcasting Rules

vector = np.array([1,2,0,0,4,0])
indices = np.array([0,1,2,3,4,5])

mascara = vector[indices] != 0
mascara_2 = indices[vector] != 0

print(vector[mascara])
print("respuesta:", indices[mascara_2])

[1 2 4]
respuesta: [0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [136]:
matriz = np.random.randint(1,55,(10,10))
matriz

array([[24,  4, 11, 19,  3, 27, 14, 11, 51, 12],
       [16, 29, 45, 45, 10, 26, 42, 32, 29, 29],
       [52, 36, 51, 41,  2, 47, 26, 42, 19,  3],
       [39, 33,  7, 45, 17, 47, 13, 29, 48, 20],
       [23, 32,  8, 43, 20, 53, 45,  8, 12, 20],
       [46, 23, 41, 18, 45, 22, 35, 32, 22, 26],
       [40, 17, 38, 51, 22, 36, 11, 45,  1, 45],
       [54,  3, 37, 21, 49, 43, 52, 34,  6, 50],
       [35, 14, 35, 17, 54, 29, 41, 30, 11, 47],
       [44, 33,  4, 46, 32, 23, 16, 50, 51, 48]])

In [143]:
print("Mínimos por fila: ",matriz.min(axis=1))
print("Máximos por fila: ",matriz.max(axis=1))

Mínimos por fila:  [ 3 10  2  7  8 18  1  3 11  4]
Máximos por fila:  [51 45 52 48 53 46 51 54 54 51]


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [165]:
a = np.arange(30)
vector = np.random.choice(a,30)
vector

array([28, 21, 10,  0, 24, 22,  0, 19, 28, 21,  8, 22, 14, 20, 15,  4, 26,
       27, 10, 17,  3,  9, 23,  6,  3, 27,  1, 12,  0,  2])

In [166]:
vector.mean()

14.066666666666666

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [179]:
externo =np.ones((4,4))

interno = externo[1:3,1:3] = 0

externo


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [191]:
np.random.randint(0,2,(8,8))

array([[1, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [303]:
a= np.random.randint(0,2)
np.tile(a,(8,8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [328]:
a= np.random.random_integers(0,2)
np.tile(a,(8,8))

C:\Users\vipre\AppData\Local\Temp\ipykernel_55140\1340052605.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 2 + 1) instead
  a= np.random.random_integers(0,2)


array([[2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2]])

In [333]:
a = np.array([0,1])
np.tile(a,(8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [251]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'c:\\Users\\vipre\\anaconda3\\envs\\EDA_ENV\\lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\vipre\anaconda3\envs\eda_env\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ==

In [192]:
np.tile?

Signature:       np.tile(A, reps)
Call signature:  np.tile(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function tile at 0x0000020B46B80D30>
File:            c:\users\vipre\anaconda3\envs\eda_env\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting op

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [337]:
matriz = np.random.randint(0,55,(5,5))
matriz

array([[46,  7,  5, 18,  6],
       [17, 49, 46, 43, 27],
       [20, 28, 30, 38, 40],
       [15, 29, 15, 52, 31],
       [34, 21,  6, 25, 28]])

In [340]:
media =np.mean(matriz)
media

27.04

In [342]:
resta = matriz -media
resta

array([[ 18.96, -20.04, -22.04,  -9.04, -21.04],
       [-10.04,  21.96,  18.96,  15.96,  -0.04],
       [ -7.04,   0.96,   2.96,  10.96,  12.96],
       [-12.04,   1.96, -12.04,  24.96,   3.96],
       [  6.96,  -6.04, -21.04,  -2.04,   0.96]])

In [344]:
desviacion = np.std(matriz)
desviacion

13.828897280694507

In [345]:
resultado = resta/desviacion
resultado

array([[ 1.37104207, -1.44913941, -1.5937641 , -0.6537036 , -1.52145175],
       [-0.72601595,  1.58797911,  1.37104207,  1.15410504, -0.00289249],
       [-0.50907891,  0.06941985,  0.21404454,  0.79254331,  0.937168  ],
       [-0.87064064,  0.1417322 , -0.87064064,  1.80491615,  0.28635689],
       [ 0.50329393, -0.43676657, -1.52145175, -0.14751719,  0.06941985]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [372]:
my_array = np.arange(11)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [392]:
mascara = my_array[3:9] = -1

my_array[mascara]
nuevo_array = my_array
nuevo_array


array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [394]:
mascara_2 = nuevo_array[3:9]*-1
mascara_2


array([1, 1, 1, 1, 1, 1])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.